import { RecoveryTeaching } from '../types/recovery';

export const RECOVERY_TEACHINGS_DATA: RecoveryTeaching[] = [
  {
    id: 'rec_teach_1',
    title: 'Celebrate Recovery: Lesson 1 - Denial',
    speaker: 'Pastor John Baker',
    duration: '28:15',
    category: 'substance',
    audioUrl: 'https://www.youtube.com/watch?v=O0i46mr2Zs4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1507692049790-de58290a4334?w=800&auto=format&fit=crop&q=80',
    scriptureRef: 'Matthew 5:3',
    description: 'The foundational first lesson of Celebrate Recovery. Discover how stepping out of denial and admitting our powerlessness is the very first step toward healing our hurts, habits, and hang-ups.',
    likesCount: 1240,
    tags: ['Denial', 'Surrender', 'Celebrate Recovery'],
    keyQuote: 'We can\'t heal what we won\'t reveal. Admitting you are powerless is where God\'s power begins.'
  },
  {
    id: 'rec_teach_2',
    title: 'Radical Deliverance from 22 Years of Addiction',
    speaker: 'Todd White',
    duration: '14:30',
    category: 'deliverance',
    audioUrl: 'https://www.youtube.com/watch?v=3FHL2mHDv3A',
    thumbnailUrl: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&auto=format&fit=crop&q=80',
    scriptureRef: '2 Corinthians 5:17',
    description: 'An incredibly powerful testimony of how the radical grace of Jesus Christ completely shattered a 22-year severe drug addiction, turning a broken atheist into an evangelist overnight.',
    likesCount: 3890,
    tags: ['Testimony', 'Deliverance', 'Grace'],
    keyQuote: 'When Jesus sets you free, He doesn\'t just modify your behavior, He gives you a brand new heart.'
  },
  {
    id: 'rec_teach_3',
    title: 'How to Break Bad Habits & Addictions',
    speaker: 'Pastor Michael Todd',
    duration: '45:12',
    category: 'purity',
    audioUrl: 'https://www.youtube.com/watch?v=Z1Bw7wdtJdc',
    thumbnailUrl: 'https://images.unsplash.com/photo-1509021436665-8f07dbf5bf1d?w=800&auto=format&fit=crop&q=80',
    scriptureRef: 'Romans 12:2',
    description: 'A deeply relatable, practical, and highly spiritual teaching on how the enemy uses habits to build strongholds, and the exact steps to rewire your mind through the Holy Spirit.',
    likesCount: 5210,
    tags: ['Mind Renewal', 'Habits', 'Transformation'],
    keyQuote: 'You cannot defeat a spiritual stronghold with physical willpower alone.'
  },
  {
    id: 'rec_teach_4',
    title: 'Breaking The Cycle of Shame',
    speaker: 'Pastor Steven Furtick',
    duration: '38:45',
    category: 'grace',
    audioUrl: 'https://www.youtube.com/watch?v=syzWK9rDyjA',
    thumbnailUrl: 'https://images.unsplash.com/photo-1470240731273-7821a6eeb6bd?w=800&auto=format&fit=crop&q=80',
    scriptureRef: 'Romans 8:1',
    description: 'Relapse and struggle often produce an overwhelming spiral of self-hatred. Learn the critical difference between the convicting voice of the Holy Spirit and the condemning lies of the accuser.',
    likesCount: 8900,
    tags: ['Shame', 'Condemnation', 'Grace'],
    keyQuote: 'The enemy wants you to focus on your performance, God wants you to focus on His provision.'
  },
  {
    id: 'rec_teach_5',
    title: 'Winning the War in Your Mind (Overcoming Anxiety)',
    speaker: 'Pastor Craig Groeschel',
    duration: '32:10',
    category: 'anxiety',
    audioUrl: 'https://www.youtube.com/watch?v=6JWDfXScGZY',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=800&auto=format&fit=crop&q=80',
    scriptureRef: '2 Corinthians 10:4-5',
    description: 'The battlefield for recovery is in the mind. A masterful teaching on how to take every thought captive, overcome deep-seated anxiety, and replace the enemy\'s lies with God\'s truth.',
    likesCount: 6100,
    tags: ['Anxiety', 'Thoughts', 'Spiritual Warfare'],
    keyQuote: 'Your life is always moving in the direction of your strongest thoughts.'
  },
  {
    id: 'rec_teach_6',
    title: 'How to Overcome an Addiction',
    speaker: 'Pastor Craig Groeschel',
    duration: '35:20',
    category: 'general',
    audioUrl: 'https://www.youtube.com/watch?v=jrvYJLInE4I',
    thumbnailUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=800&auto=format&fit=crop&q=80',
    scriptureRef: '1 Corinthians 10:13',
    description: 'A direct, compassionate, and fiercely biblical roadmap for anyone trapped in the cycle of addiction, demonstrating how the Holy Spirit provides an exit door for every temptation.',
    likesCount: 4200,
    tags: ['Addiction', 'Holy Spirit', 'Victory'],
    keyQuote: 'Willpower doesn\'t work because the problem isn\'t just physical; it\'s deeply spiritual. You need God\'s power.'
  },
  {
    id: 'rec_teach_7',
    title: 'Celebrate Recovery: Amends & Restitution',
    speaker: 'Pastor John Baker',
    duration: '22:15',
    category: 'deliverance',
    audioUrl: 'https://www.youtube.com/watch?v=owK5LV7TJCY',
    thumbnailUrl: 'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?w=800&auto=format&fit=crop&q=80',
    scriptureRef: 'Matthew 5:23-24',
    description: 'A core Celebrate Recovery teaching on how to effectively make amends and seek restitution with the people harmed by our past habits, without causing further injury.',
    likesCount: 2150,
    tags: ['Amends', 'Restitution', 'Healing'],
    keyQuote: 'Forgiveness is letting go of the past, but making amends is clearing the path for the future.'
  },
  {
    id: 'rec_teach_8',
    title: 'Rewiring Your Mind with the Word',
    speaker: 'Pastor Craig Groeschel',
    duration: '29:40',
    category: 'purity',
    audioUrl: 'https://www.youtube.com/watch?v=u-ZyyUGDRtU',
    thumbnailUrl: 'https://images.unsplash.com/photo-1491841550275-ad7854e35ca6?w=800&auto=format&fit=crop&q=80',
    scriptureRef: 'Romans 12:2',
    description: 'An advanced look at neuroplasticity and the Bible. Discover how immersing yourself in Scripture literally rewires the brain, overwriting old addictive pathways with God\'s truth.',
    likesCount: 7800,
    tags: ['Mind Renewal', 'Scripture', 'Transformation'],
    keyQuote: 'You cannot change your life until you change your thoughts, and you cannot change your thoughts without the Word of God.'
  },
  {
    id: 'rec_teach_9',
    title: 'How to Fight Sin Everyday',
    speaker: 'John Piper',
    duration: '18:20',
    category: 'anxiety',
    audioUrl: 'https://www.youtube.com/watch?v=lDRQzHz_0iY',
    thumbnailUrl: 'https://images.unsplash.com/photo-1513258496099-48168024aec0?w=800&auto=format&fit=crop&q=80',
    scriptureRef: 'Galatians 5:16',
    description: 'A powerful exhortation on daily spiritual vigilance. Piper breaks down why we must actively fight sin through faith in a superior promise, not just relying on willpower.',
    likesCount: 5120,
    tags: ['Vigilance', 'Spiritual Warfare', 'Faith'],
    keyQuote: 'Sin is what you do when your heart is not satisfied with God. Fight sin with a superior satisfaction.'
  },
  {
    id: 'rec_teach_10',
    title: 'Turn Your Pain Into Purpose',
    speaker: 'Christine Caine',
    duration: '41:10',
    category: 'grace',
    audioUrl: 'https://www.youtube.com/watch?v=aIrwb3unP4A',
    thumbnailUrl: 'https://images.unsplash.com/photo-1490730141103-6cac27aaab94?w=800&auto=format&fit=crop&q=80',
    scriptureRef: '2 Corinthians 1:3-4',
    description: 'Your recovery is not just about you—it is preparation for your ministry. Discover how God takes the deepest trauma, shame, and brokenness and uses it to rescue others.',
    likesCount: 9240,
    tags: ['Purpose', 'Ministry', 'Testimony'],
    keyQuote: 'God will never waste your pain. The very thing the enemy meant to destroy you will become your greatest weapon to set others free.'
  }
];
